# Generated by Django 4.1.3 on 2022-11-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_product_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Toptext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=150)),
                ("slug", models.SlugField(max_length=150, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Bildirim",
                "verbose_name_plural": "Bildirimler",
                "ordering": ("name",),
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, upload_to="static"),
        ),
    ]
