# Generated by Django 4.1.3 on 2022-11-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_toptext_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="toptext",
            name="date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterIndexTogether(
            name="toptext",
            index_together={("id", "slug")},
        ),
        migrations.RemoveField(
            model_name="toptext",
            name="description",
        ),
    ]
